### ISSUE TITLE
Why not use `Control.Monad.State`?

### ISSUE THREAD

**Issue by ice1000** [Trebor-Huang/typical-math#5]
https://github.com/Trebor-Huang/typical-math/blob/4ccdf4c0b017d98bb5dd7e9317295f6e24bb356b/Knowledge.hs#L58

**Comment by Trebor-Huang** [comment]
qwq I'm learning Haskell at that stage, and it's far more beneficial for me to write that out explicitly. Will rewrite the whole thing soon.
